version: '3.1'

services:
    # In this docker-compose are deployed the Openvidu services.
    # This file not necessary change, you only need change 
    # the .env file with the necessaries variables.
    openvidu-server:
        image: openvidu/openvidu-server:2.13.0-beta1
        restart: on-failure
        network_mode: host
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${OPENVIDU_RECORDING_FOLDER}:${OPENVIDU_RECORDING_FOLDER}
        env_file: 
            - .env
        environment:
            - SERVER_SSL_ENABLED=false
            - SERVER_PORT=5443
            - OPENVIDU_SECRET=${OPENVIDU_SECRET}
            - OPENVIDU_PUBLICURL=
            - OPENVIDU_RECORDING=true
            - OPENVIDU_RECORDING_PATH=${OPENVIDU_RECORDING_FOLDER}
            - KMS_URIS="[\"ws://127.0.0.1:8888/kurento\"]"
            - COTURN_IP=${OPENVIDU_DOMAIN_OR_PUBLIC_IP}
            - COTURN_REDIS_IP=127.0.0.1
            - LOGGING_LEVEL_ROOT=${OV_CE_DEBUG_LEVEL:-INFO}

    kms:
        image: kurento/${KMS_IMAGE:-kurento-media-server-dev:6.13}
        restart: on-failure
        network_mode: host
        environment:
            - KMS_EXTERNAL_ADDRESS=auto
            - KMS_MIN_PORT=40000
            - KMS_MAX_PORT=57000
            - GST_DEBUG=${KMS_DEBUG_LEVEL:-3,Kurento*:4,kms*:4,sdp*:4,webrtc*:4,*rtpendpoint:4,rtp*handler:4,rtpsynchronizer:4,agnosticbin:4}

    redis:
        image: redis:5.0.7
        restart: on-failure
        network_mode: host

    coturn:
        image: openvidu/openvidu-coturn:1.0.0-beta1
        restart: on-failure
        network_mode: host
        environment:
            - REDIS_IP=127.0.0.1
            - TURN_LISTEN_PORT=3478
            - DB_NAME=0
            - DB_PASSWORD=turn
            - MIN_PORT=57001
            - MAX_PORT=65535
        
    nginx:
        image: openvidu/openvidu-proxy:1.0.0-beta1
        restart: on-failure
        network_mode: host
        volumes:
            - ./certificates:/etc/letsencrypt
            - ./owncert:/owncert
        environment: 
            - DOMAIN_OR_PUBLIC_IP=${OPENVIDU_DOMAIN_OR_PUBLIC_IP}
            - CERTIFICATE_TYPE=${CERTIFICATE_TYPE}
            - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
