version: '3.1'

services:
    openvidu-server:
        image: openvidu/openvidu-server:2.13.0-beta1
        entrypoint: ["java", "-jar", "/openvidu-server.jar"]
        restart: on-failure
        network_mode: host
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${OPENVIDU_RECORDING_FOLDER}:${OPENVIDU_RECORDING_FOLDER}
        environment:
            - SERVER_SSL_ENABLED=false
            - SERVER_PORT=5443
            - OPENVIDU_PUBLICURL=https://${DOMAIN_OR_PUBLIC_IP}
            - OPENVIDU_SECRET=${OPENVIDU_SECRET}
            - OPENVIDU_RECORDING=true
            - OPENVIDU_RECORDING_PATH=${OPENVIDU_RECORDING_FOLDER}
            - KMS_URIS="[\"ws://127.0.0.1:8888/kurento\"]"
            - COTURN_IP=${DOMAIN_OR_PUBLIC_IP}
            - COTURN_REDIS_IP=127.0.0.1

    kms:
        image: kurento/kurento-media-server:6.13.0
        restart: on-failure
        network_mode: host
        environment:
            - KMS_EXTERNAL_ADDRESS=auto

    redis-db:
        image: redis:5.0.7
        restart: on-failure
        network_mode: host

    openvidu-coturn:
        image: openvidu/openvidu-coturn:1.0.0-beta1
        restart: on-failure
        network_mode: host
        environment:
            - REDIS_IP=127.0.0.1
            - TURN_LISTEN_PORT=3478
            - DB_NAME=0
            - DB_PASSWORD=turn
            - MIN_PORT=40000
            - MAX_PORT=65535
        
    openvidu-proxy:
        image: openvidu/openvidu-proxy:1.0.0-beta1
        restart: on-failure
        network_mode: host
        volumes:
            - ./nginx_conf:/nginx_conf
            - ./owncert:/owncert
        environment: 
            - DOMAIN_OR_PUBLIC_IP=${DOMAIN_OR_PUBLIC_IP}
            - CERTIFICATE_TYPE=${CERTIFICATE_TYPE}
            - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

    openvidu-call:
        image: openvidu/openvidu-call:2.13.0-beta1
        restart: on-failure
        ports:
            - "5442:80"
        environment: 
            - OPENVIDU_URL=https://${DOMAIN_OR_PUBLIC_IP}
            - OPENVIDU_SECRET=${OPENVIDU_SECRET}

